buildscript {
    repositories {
        google()
        mavenCentral() // الأولوية لهذا المستودع الآن
    }
    dependencies {
        // نسخة Plugin متوافقة مع Gradle 8.x
        classpath 'com.android.tools.build:gradle:7.4.2' 
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:2.5.3"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
